spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bizhengyong/config-repo.git
          username: bizhengyong
          password: zheng358716671.
          basedir: E:\workspace\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/